version: '3.8'
services:
  mysqldb:
    container_name: mysqlcontainer
    image: mysql:oracle
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "587Rich587."
      MYSQL_DATABASE: patientsdb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mysqldb
      DB_USER: 'root'
      DB_PASSWORD: '587Rich587.'
      DB_NAME: patients
      DB_PORT: 3306 # Puerto predeteminado para MySQL.
      DB_CONNECTION_LIMIT: 10 # Limite de conexiones simultaneas a la DB
      SERVER_PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge